name: deploy using liquibase
on: 
  push:
    branches: ['develop']

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: liquibase/liquibase:latest
    steps:
      - name: Show liquibase version
        run: liquibase -v
    