name: Deploy SQLs
on: [push]

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'update'
          classpath: 'example/changelogs'
          changeLogFile: 'sample-changelog.sql'
          db: 'SHOP'
          warehouse: 'COMPUTE_WH'
          schema: 'PUBLIC'
          username: ${{ secrets.APP_USER }}
          password: ${{ secrets.APP_PASS }}
          url: ${{ secrets.SF_URL }}