name: Deploy SQLs
on: [push]

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'rollback'
          classpath: 'example/changelogs'
          changeLogFile: 'example/changelogs/sample-changelog.sql'
          username: ${{ secrets.APP_USER }}
          password: ${{ secrets.APP_PASS }}
          url: jdbc:snowflake://ie67702.southeast-asia.azure.snowflakecomputing.com:443/?db=SHOP&warehouse=COMPUTE_WH&schema=PUBLIC
